model_name_or_path: Qwen/Qwen3-Coder-30B-A3B-Instruct
#model_name_or_path: Qwen/Qwen3-4B-Instruct-2507
trust_remote_code: true
deepspeed: ds_z3_config.json

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
#lora_target: q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj
lora_rank: 32 #32
lora_alpha: 16
lora_dropout: 0.1

### dataset
dataset: train
template: qwen3_nothink
cutoff_len: 4096
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

# output
output_dir: factory_qwen_results
logging_steps: 10
save_steps: 30
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
gradient_checkpointing: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-4 #3.0e-4
num_train_epochs: 3.0 #9.0
lr_scheduler_type: cosine #constant
compute_accuracy: true
include_effective_tokens_per_second: true
warmup_steps: 100
ddp_timeout: 180000000
ddp_backend: nccl
bf16: true
resume_from_checkpoint: null

save_total_limit: 1
load_best_model_at_end: true
metric_for_best_model: eval_loss

### evaluate
eval_dataset: test
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 30